version: 2.1
orbs:
  node: circleci/node@5.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.15.1
    steps:
      - checkout
      - run:
          name: set registry token
          command: npm config set '//npm.pkg.github.com/:_authToken' $GITHUB_AUTH_TOKEN
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn run build
      - run: yarn run lint
      - run: yarn run test
      - run: yarn run size-limit
  build-test-and-publish:
    docker:
      - image: cimg/node:16.15.1
    steps:
      - checkout
      - run:
          name: set registry token
          command: npm config set '//npm.pkg.github.com/:_authToken' $GITHUB_AUTH_TOKEN
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn run build
      - run: yarn run lint
      - run: yarn run test
      - run: yarn run size-limit
      - run: yarn npm publish
      - run: yarn run postpublish

workflows:
  build-and-test:
    jobs:
      - build-and-test:
          context: izi-main-context
          filters:
            branches:
              ignore:
                - master
                - gh-pages
  build-test-and-publish:
    jobs:
      - build-test-and-publish:
          context: izi-main-context
          filters:
            branches:
              only: master
